### ISSUE TITLE
TypeError: 'int' object is not iterable

### ISSUE THREAD

**Issue by bhanga-manish** [evfro/polara#9] opened 2020-04-07 21:42 UTC
Hi,
While running data_model.prepare(), There is error on following line.
`features_melted = self.item_features.agg(lambda x: [f for l in x for f in l], axis=1)`

Error is  _TypeError: 'int' object is not iterable_

However I tried converting every element in the item_tag dataframe in str then into np array, But doesn't seem to work.

**Comment by evfro** [comment] 2020-04-08 18:00
Hi,

I believe the problem is with your `item_features` object. Could you show its content?

**Comment by bhanga-manish** [comment] 2020-04-08 19:35
Hi evfro,
Here is item_features Dataframe.

![image](https://user-images.githubusercontent.com/25792910/78825672-02920700-79fe-11ea-8060-12a030acac77.png)

**Comment by evfro** [comment] 2020-04-09 03:24
The problematic part is your `id` column:
- if it's a feature than you should convert every value of this column to a list, e.g., 1 must become [1];
- if it's an actual index of an item, you should run `item_tags = item_tags.set_index("id")`.

Note that in the latter case this index must be the same as the index in your training data. See the example in my blog: the training, the test, and the item feature datasets are printed above the section titled `Preparing data model for training and validation`: https://www.eigentheories.com/blog/lightfm-vs-hybridsvd/#Preparing-data-model-for-training-and-validation

**Comment by evfro** [comment] 2020-04-20 19:04
@bhanga-manish have you been able to resolve the problem with the hints above?

**Comment by evfro** [comment] 2021-01-07 06:45
Closing this as the issue seem to be resolved. Feel free to reopen if you still have problems.

**Closed by evfro** 2021-01-07 06:45 UTC
