### ISSUE TITLE
ModuleNotFoundError: No module named 'polara.recommender'

### ISSUE THREAD

**Issue by bhanga-manish** [evfro/polara#7] opened 2020-03-29 13:08 UTC
Not able to install using python 3.7.7 venv with following requirement versions.
jupyter>=1.0.0
numba>=0.21.0
numpy>=1.10.1
matplotlib>=1.4.3
pandas>=0.17.1
requests>=2.7.0
scipy>=0.16.0

**Comment by evfro** [comment] 2020-03-29 13:27
Thanks for reporting. I'll have a look. Could you also specify the version of setuptools in your environment and which version of OS you're using?

**Comment by bhanga-manish** [comment] 2020-03-29 13:53
setuptools: 46.1.3
OS: Ubuntu 18.04.4 LTS

**Comment by evfro** [comment] 2020-04-20 19:02
@bhanga-manish unfortunately, I'm unable to reproduce this problem on my local machine. Can you provide more details how did you install polara? Have you installed it directly from github or via cloned repository? Have you installed it in the developer mode (editable) or as a standard package?
Also, I noticed that python 3.7.7 version is removed from the conda-forge channel due to compatibility issues. Could you try your setup on python 3.7.6 or on some 3.8+ version?

**Comment by evfro** [comment] 2021-01-07 06:43
Since the version of polara have been updated, I'm closing this issue. Feel free to reopen/open a new one if you still have problems with it.

**Closed by evfro** 2021-01-07 06:43 UTC

**Comment by shalinikaripe** [comment] 2022-03-10 07:07
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Input In [50], in <module>
----> 1 from polara.recommender.coldstart.models import LightFMItemColdStart

ModuleNotFoundError: No module named 'polara'

even after doing pip install polara also facing the issue - ModuleNotFoundError: No module named 'polara'
